version: '3.8'
services:
  social-networking-app:
    build: .
    ports:
      - '3001:3000'
    env_file:
      - .env
    depends_on:
      - mysql-db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start

  mysql-db:
    image: mysql/mysql-server:8.0
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: {}
